# Make a new entry
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Four",
    "number": "444-444-444"
}

###
# delete id: 656648047aa4a5057622077f
DELETE http://localhost:3001/api/persons/656648047aa4a5057622077f

###
# get all
GET http://localhost:3001/api/persons

###
# get 65662f3247f558952be88b1f
GET http://localhost:3001/api/persons/65662f3247f558952be88b1f
###
# get unexisting
GET http://localhost:3001/api/persons/65662f3247f558952be88b1e


###
# info
GET http://localhost:3001/info

# Bad requests:
###
# Missing name
POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "9001"
}

###
# Missing number
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Numberless"
}
